baseurl = "/"
languageCode = "en-us"
title = "Strativerse"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
    description = "A collection of time-stratigraphic publications."

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
    gitHubRepo = "paleolimbot/strativerse-hugo"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[taxonomies]
    publication = "publications"
    
