baseurl = "/"
languageCode = "en-us"
title = "Strativerse"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "JSON" ]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    
[[menu.main]]
    name = "About"
    url = "/about/"

[params]
    description = "A collection of time-stratigraphic publications."

    # path to the favicon, under "static"
    favicon = "images/logo.png"
    
    gitHubRepo = "paleolimbot/strativerse-hugo"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[taxonomies]
    publication = "publications"
    parameter = "parameters"
    person = "people"
    record = "records"
    feature = "features"
